export enum TaskActionTypes {
  SET_IS_LOADING = 'TASK/SET_IS_LOADING',
  SET_ERROR = 'TASK/ERROR',
  SET_TASKS = 'TASK/SET_TASKS',
  SET_IS_SUCCESS = 'TASK/SET_IS_SUCCESS',
  SET_FILTERS = 'TASK/SET_FILTERS',
  SET_META = 'TASK/SET_META',
  SET_META_CURRENT_PAGE = 'TASK/SET_META_CURRENT_PAGE'
}
